[tool.poetry]
name = "leagueverse"
version = "0.1.0"
description = ""
authors = ["nxbringr <bpakhi97@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.54.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
